= YesDay System Utilities (ydsu)
Doc Writer <yesdayuk@gmail.com>
v1.0, 2019-11-03
:toc: macro
toc::[]
:numbered:

== About

YesDay System Utilities (ydsu), pronounced `i'dsʊ`, is a package manager for your shell scripts. Primarily targeted for use by Developers, SysAdmins, Power Users, DevOps and Operations Engineers, ydsu is designed to encourage modification of the shell scripts in an IDE-friendly way. Shell scripts of relevant functionality are grouped together into modules and are managed by the management scripts provided by ydsu. Modules can be either external, developed by a third party, or your own. You specify the list of modules you want to use inside the `module.yml` file. Your local configuration of modules inside the `module.yml` is called a distribution.

Advantages

* *Lightweight* - Only requires git, ansible and groovy to be present on your system. Even works with ZSH too. *~2k* lines of code.
* *Multi-platform* - Runs on any UNIX based platforms: Mac OSX, Linux, Cygwin, Solaris and FreeBSD.
* *Modular and easy to extend* - You can create modules for your own individual needs and/or make them available to the public. Even ydsu itself is implemented as a set of two (internal) modules: `manage` and `util`. More so, if you write your modules in a JVM language, you can take advantage of the internal module `util`.
* *Polyglot* - Write your modules in any programming language: Groovy, Bash, Kotlin, Java, Python, Go, Ruby, Node.js, Rust, Dlang, you name it. Ydsu will manage them in the same way.
* *Distributed - no lock-in* - Store your modules in any private or public git repository. Ydsu will take care of the rest. Even ydsu itself can be hosted on and installed from your own private repository. It is designed from the ground up NOT to lock you into any specific repository.
* *Can operate in any network or even air-gaped environment* - Ydsu can be used in internet/intranet/LAN or even air-gaped environments. No matter what environment you are in, you can take full advantage of the features.
* *Lines of Code (LOC) and Code Quality* - Well written, clean and high quality codebase: 1952 lines of groovy code, 139 lines of bash code, 26% comments, 27 groovy files, 2 bash files, 72 lines per file on average.

== Install

Paste and run the following in a terminal:
`$ curl -s "https://raw.githubusercontent.com/yesday/ydsu/master/src/main/bash/install/ydsu-install.sh" | bash`

== Usage

Install

* *ydsu-install.sh*: Installs ydsu on your local system. A bash script that clones ydsu to `~/appdata/ydsu/source/yesday/ydsu` and checks for the prerequisites `git`, `groovy` and `ansible`. Also, adds the ansible-managed block for ydsu's system path to `.extend.bashrc` and `.extend.zshrc`.
* *ydsuUninstall*: Uninstalls ydsu from your local system. A groovy script that removes the ansible-managed block for ydsu's system path from `.extend.bashrc` and `.extend.zshrc`. Also, clears the `~/appdata/ydsu/cache` and `~/appdata/ydsu/source/yesday/ydsu` directories.

Configure

* ~/appdata/ydsu/conf/yesday-ydsu-manage/*module.yml*: Create or edit this file to specify the list of modules you wish to use. Also, as described in <<Configuration guide for module.yml>>, it is recommended to maintain the content of the distribution directory `yesday-ydsu-manage` in a git repository.
* *ydsuLoadModules*: Loads the changes from the above `module.yml` file. Git clones modules into `~/appdata/ydsu/cache/yesday-ydsu-manage/source/` and/or removes the ones that are no longer present inside the `module.yml` file. Updates the ansible-managed block for ydsu's system path inside `.extend.bashrc` and `.extend.zshrc`. Configures Groovy Compiler's classpath inside `~/appdata/ydsu/conf/yesday-ydsu-manage/groovyCompilerConf.groovy`. Note that this command will not update existing modules, which can be done by the `ydsuPull` command documented below.

Use

* *skeletonListCommands*: Execute this groovy script to verify the installation. The script comes as part of the `skeleton` module which is pre-configured inside the `module.yml` of the default distribution.

Extend

* Create a new module and push it to a local or remote git repository. A module can contain anything that would work by adding it to your system path, such as a bash or groovy shell script. Use the `skeleton` module as a blueprint for your own modules.
* ~/appdata/ydsu/conf/yesday-ydsu-manage/*module.yml*: Create or edit the `module.yml` file to add the new module into your distribution.
* *ydsuLoadModules*: Always remember to run `ydsuLoadModules` after modifying `module.yml` in order for the changes to take effect.

Maintain

* *ydsuPull*: Git pulls module updates for every module inside `~/appdata/ydsu/cache/yesday-ydsu-manage/source/`. Also, updates ydsu itself, including the files `ydsuLoadModules`, `ydsuPull` and `ydsuUninstall` under the `~/appdata/ydsu/source/yesday/ydsu` directory.

== Configuration guide for module.yml

A module is a number of shell scripts of relevant functionality that are grouped together into a directory. The module directory is usually versioned and is part of a project structure, such as the gradle's directory layout for a groovy application (e.g. `gradle init --type groovy-application`). The latter is to encourage modification of the shell scripts in an IDE-friendly way. Modules can be either external, developed by a third party, or your own. A module is configured by specifying a local or remote path. The path can refer to either a single module or a collection of modules. Following is an example of a `module.yml` that demonstrates the configuration of a public module, a local collection of modules, and a single local module.

.module.yml
[source, yaml]
----
module:
  - https://github.com/yesday/ydsu-module/master/src/main/groovy/ydsu/module/skeleton // <1>
  - ~/my-ydsu-module/src/main/groovy/ydsu/module // <2>
  - ~/mycompany-ydsu-module/src/main/groovy/ydsu/module/mycompany // <3>
----

<1> Remote path to a module. The module will be automatically cloned into `~/appdata/ydsu/cache/yesday-ydsu-manage/source/yesday/ydsu-module/src/main/groovy/ydsu/module/skeleton` by the `ydsuLoadModules` management script. Note the use of the master branch encoded into the URL.
<2> Local path to a list of modules. The path can be a plain directory or a local git repository. Local paths are used as is without being copied into the `~/appdata/ydsu/cache/yesday-ydsu-manage/source` directory.
<3> Local path to a single module, which includes scripts relevant to your work environment.

If the local directory has at least one regular file then it is a single module. Otherwise, it's a collection of modules. Hidden files like `.DS_Store` are NOT taken into account.

Your local configuration of modules inside the `module.yml` is called a distribution. The `module.yml` file is stored in the directory `~/appdata/ydsu/conf/yesday-ydsu-manage/`. It is recommended to maintain the content of this directory in a git repository. For example, you can clone any external/internal distribution that is tailored to your needs: `rm -rf ~/appdata/ydsu/conf/yesday-ydsu-manage; git clone https://github.com/yesday/ydsu-distribution-macos.git ~/appdata/ydsu/conf/yesday-ydsu-manage`.

== Module development

You can write your modules in any programming language: Groovy, Bash, Kotlin, Java, Python, Go, Ruby, Node.js, you name it. Ydsu will manage them in the same way.

If you write your modules in a JVM language, you can take advantage of the internal module `util`. To do so, simply add the `ydsu` maven package to your module's project dependencies.

To compile the ydsu project and publish the maven artifact to your local repository type

 ./gradlew clean publishToMavenLocal

Then you can add the project as a dependency to your own `build.gradle` configuration as follows

.build.gradle
[source, groovy]
----
dependencies {
    implementation group: 'io.github.yesday', name: 'ydsu', version: '1.0.0-SNAPSHOT'
}
----

Finally, the `skeleton` module, that comes pre-configured as part of the default distribution, can be used as a blueprint for your own modules. Simply make a copy of the gradle project `~/appdata/ydsu/cache/yesday-ydsu-manage/source/yesday/ydsu-module`, then open it with your favourite IDE, and happy coding!
