#!/usr/bin/env bash
# This script is used as shebang by groovy shell scripts
# https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
GROOVY_COMPILER_CONF="$DIR/conf/groovyCompilerConf.groovy"
OVERRIDDEN_GROOVY_COMPILER_CONF="$HOME/appdata/ydsu/conf/yesday-ydsu-manage/groovyCompilerConf.groovy"
if [ -f "$OVERRIDDEN_GROOVY_COMPILER_CONF" ]; then
  GROOVY_COMPILER_CONF=$OVERRIDDEN_GROOVY_COMPILER_CONF
fi
groovy --configscript "$GROOVY_COMPILER_CONF" -Dlogback.configurationFile="$DIR/../../../../resources/logback.groovy" "$@"
